In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns 
import os

In [30]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/open-university-learning-analytics-dataset/studentRegistration.csv
/kaggle/input/open-university-learning-analytics-dataset/studentAssessment.csv
/kaggle/input/open-university-learning-analytics-dataset/studentInfo.csv
/kaggle/input/open-university-learning-analytics-dataset/studentVle.csv
/kaggle/input/open-university-learning-analytics-dataset/vle.csv
/kaggle/input/open-university-learning-analytics-dataset/assessments.csv
/kaggle/input/open-university-learning-analytics-dataset/courses.csv
/kaggle/input/open-university-learning-analytics-dataset/anonymiseddata/studentRegistration.csv
/kaggle/input/open-university-learning-analytics-dataset/anonymiseddata/studentAssessment.csv
/kaggle/input/open-university-learning-analytics-dataset/anonymiseddata/studentInfo.csv
/kaggle/input/open-university-learning-analytics-dataset/anonymiseddata/studentVle.csv
/kaggle/input/open-university-learning-analytics-dataset/anonymiseddata/vle.csv
/kaggle/input/open-university-learning-analytics-dataset/anonymiseddata/assessments.csv
/kaggle/input/open-university-learning-analytics-dataset/anonymiseddata/courses.csv

In [31]:
assessments = pd.read_csv('/kaggle/input/open-university-learning-analytics-dataset/assessments.csv')
courses = pd.read_csv('/kaggle/input/open-university-learning-analytics-dataset/courses.csv')
student_assessments = pd.read_csv('/kaggle/input/open-university-learning-analytics-dataset/studentAssessment.csv')
student_info = pd.read_csv('/kaggle/input/open-university-learning-analytics-dataset/studentInfo.csv')
registration = pd.read_csv('/kaggle/input/open-university-learning-analytics-dataset/studentRegistration.csv')
student_vle= pd.read_csv('/kaggle/input/open-university-learning-analytics-dataset/studentVle.csv')
vle = pd.read_csv('/kaggle/input/open-university-learning-analytics-dataset/vle.csv')

datasets = {
    'assessments':assessments,
    'courses':courses,
    'student_assessments':student_assessments,
    'student_info':student_info,
    'registration':registration,
    'student_vle':student_vle,
    'vle':vle}

In [32]:
def basic_exploration(name, df):
    print("{}.head()".format(name))
    print(df.head())
    print("{}.shape".format(name))
    print(df.shape)
    print("\n{}.describe()".format(name))
    print(df.describe(include='all'))
    print("\n{}.isna().sum()".format(name))
    print(df.isna().sum())
    print("\n{}.value_counts()".format(name))
    print(df.value_counts())
    
    #matrix = df.corr()
    #plotting correlation matrix 
    #sns.heatmap(matrix, cmap="Greens", annot=True)
    print("\n")

#basic_exploration("assessments", assessments)

In [33]:
for name, df in datasets.items():
    #(name)
    basic_exploration(name, df)

assessments.head()
  code_module code_presentation  id_assessment assessment_type   date  weight
0         AAA             2013J           1752             TMA   19.0    10.0
1         AAA             2013J           1753             TMA   54.0    20.0
2         AAA             2013J           1754             TMA  117.0    20.0
3         AAA             2013J           1755             TMA  166.0    20.0
4         AAA             2013J           1756             TMA  215.0    30.0
assessments.shape
(206, 6)

assessments.describe()
       code_module code_presentation  id_assessment assessment_type  \
count          206               206     206.000000             206
unique           7                 4            NaN               3
top            FFF             2014J            NaN             TMA
freq            52                57            NaN             106
mean           NaN               NaN   26473.975728             NaN
std            NaN               NaN   10098.625521             NaN
min            NaN               NaN    1752.000000             NaN
25%            NaN               NaN   15023.250000             NaN
50%            NaN               NaN   25364.500000             NaN
75%            NaN               NaN   34891.750000             NaN
max            NaN               NaN   40088.000000             NaN

              date      weight
count   195.000000  206.000000
unique         NaN         NaN
top            NaN         NaN
freq           NaN         NaN
mean    145.005128   20.873786
std      76.001119   30.384224
min      12.000000    0.000000
25%      71.000000    0.000000
50%     152.000000   12.500000
75%     222.000000   24.250000
max     261.000000  100.000000

assessments.isna().sum()
code_module           0
code_presentation     0
id_assessment         0
assessment_type       0
date                 11
weight                0
dtype: int64

assessments.value_counts()
code_module  code_presentation  id_assessment  assessment_type  date   weight
AAA          2013J              1752           TMA              19.0   10.0      1
FFF          2014B              34893          CMA              227.0  0.0       1
             2013B              34871          CMA              222.0  0.0       1
                                34872          Exam             222.0  100.0     1
             2013J              34873          TMA              19.0   12.5      1
                                                                                ..
DDD          2013B              25337          TMA              116.0  15.0      1
                                25338          TMA              151.0  15.0      1
                                25339          TMA              200.0  15.0      1
                                25340          Exam             240.0  100.0     1
GGG          2014J              37444          Exam             229.0  100.0     1
Name: count, Length: 195, dtype: int64


courses.head()
  code_module code_presentation  module_presentation_length
0         AAA             2013J                         268
1         AAA             2014J                         269
2         BBB             2013J                         268
3         BBB             2014J                         262
4         BBB             2013B                         240
courses.shape
(22, 3)

courses.describe()
       code_module code_presentation  module_presentation_length
count           22                22                   22.000000
unique           7                 4                         NaN
top            BBB             2014J                         NaN
freq             4                 7                         NaN
mean           NaN               NaN                  255.545455
std            NaN               NaN                   13.654677
min            NaN               NaN                  234.000000
25%            NaN               NaN                  241.000000
50%            NaN               NaN                  261.500000
75%            NaN               NaN                  268.000000
max            NaN               NaN                  269.000000

courses.isna().sum()
code_module                   0
code_presentation             0
module_presentation_length    0
dtype: int64

courses.value_counts()
code_module  code_presentation  module_presentation_length
AAA          2013J              268                           1
             2014J              269                           1
GGG          2014B              241                           1
             2013J              261                           1
FFF          2014J              269                           1
             2014B              241                           1
             2013J              268                           1
             2013B              240                           1
EEE          2014J              269                           1
             2014B              241                           1
             2013J              268                           1
DDD          2014J              262                           1
             2014B              241                           1
             2013J              261                           1
             2013B              240                           1
CCC          2014J              269                           1
             2014B              241                           1
BBB          2014J              262                           1
             2014B              234                           1
             2013J              268                           1
             2013B              240                           1
GGG          2014J              269                           1
Name: count, dtype: int64


student_assessments.head()
   id_assessment  id_student  date_submitted  is_banked  score
0           1752       11391              18          0   78.0
1           1752       28400              22          0   70.0
2           1752       31604              17          0   72.0
3           1752       32885              26          0   69.0
4           1752       38053              19          0   79.0
student_assessments.shape
(173912, 5)

student_assessments.describe()
       id_assessment    id_student  date_submitted      is_banked  \
count  173912.000000  1.739120e+05   173912.000000  173912.000000
mean    26553.803556  7.051507e+05      116.032942       0.010977
std      8829.784254  5.523952e+05       71.484148       0.104194
min      1752.000000  6.516000e+03      -11.000000       0.000000
25%     15022.000000  5.044290e+05       51.000000       0.000000
50%     25359.000000  5.852080e+05      116.000000       0.000000
75%     34883.000000  6.344980e+05      173.000000       0.000000
max     37443.000000  2.698588e+06      608.000000       1.000000

               score
count  173739.000000
mean       75.799573
std        18.798107
min         0.000000
25%        65.000000
50%        80.000000
75%        90.000000
max       100.000000

student_assessments.isna().sum()
id_assessment       0
id_student          0
date_submitted      0
is_banked           0
score             173
dtype: int64

student_assessments.value_counts()
id_assessment  id_student  date_submitted  is_banked  score
1752           11391       18              0          78.0     1
34871          1464952     213             0          76.0     1
               1097354     223             0          80.0     1
               1118284     207             0          94.0     1
               1337055     199             0          83.0     1
                                                              ..
24294          693182      207             0          52.0     1
               693204      207             0          59.0     1
               693302      199             0          88.0     1
               693747      207             0          73.0     1
37443          2648187     215             0          80.0     1
Name: count, Length: 173739, dtype: int64


student_info.head()
  code_module code_presentation  id_student gender                region  \
0         AAA             2013J       11391      M   East Anglian Region
1         AAA             2013J       28400      F              Scotland
2         AAA             2013J       30268      F  North Western Region
3         AAA             2013J       31604      F     South East Region
4         AAA             2013J       32885      F  West Midlands Region

       highest_education imd_band age_band  num_of_prev_attempts  \
0       HE Qualification  90-100%     55<=                     0
1       HE Qualification   20-30%    35-55                     0
2  A Level or Equivalent   30-40%    35-55                     0
3  A Level or Equivalent   50-60%    35-55                     0
4     Lower Than A Level   50-60%     0-35                     0

   studied_credits disability final_result
0              240          N         Pass
1               60          N         Pass
2               60          Y    Withdrawn
3               60          N         Pass
4               60          N         Pass
student_info.shape
(32593, 12)

student_info.describe()
       code_module code_presentation    id_student gender    region  \
count        32593             32593  3.259300e+04  32593     32593
unique           7                 4           NaN      2        13
top            BBB             2014J           NaN      M  Scotland
freq          7909             11260           NaN  17875      3446
mean           NaN               NaN  7.066877e+05    NaN       NaN
std            NaN               NaN  5.491673e+05    NaN       NaN
min            NaN               NaN  3.733000e+03    NaN       NaN
25%            NaN               NaN  5.085730e+05    NaN       NaN
50%            NaN               NaN  5.903100e+05    NaN       NaN
75%            NaN               NaN  6.444530e+05    NaN       NaN
max            NaN               NaN  2.716795e+06    NaN       NaN

            highest_education imd_band age_band  num_of_prev_attempts  \
count                   32593    31482    32593          32593.000000
unique                      5       10        3                   NaN
top     A Level or Equivalent   20-30%     0-35                   NaN
freq                    14045     3654    22944                   NaN
mean                      NaN      NaN      NaN              0.163225
std                       NaN      NaN      NaN              0.479758
min                       NaN      NaN      NaN              0.000000
25%                       NaN      NaN      NaN              0.000000
50%                       NaN      NaN      NaN              0.000000
75%                       NaN      NaN      NaN              0.000000
max                       NaN      NaN      NaN              6.000000

        studied_credits disability final_result
count      32593.000000      32593        32593
unique              NaN          2            4
top                 NaN          N         Pass
freq                NaN      29429        12361
mean          79.758691        NaN          NaN
std           41.071900        NaN          NaN
min           30.000000        NaN          NaN
25%           60.000000        NaN          NaN
50%           60.000000        NaN          NaN
75%          120.000000        NaN          NaN
max          655.000000        NaN          NaN

student_info.isna().sum()
code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                1111
age_band                   0
num_of_prev_attempts       0
studied_credits            0
disability                 0
final_result               0
dtype: int64

student_info.value_counts()
code_module  code_presentation  id_student  gender  region                highest_education      imd_band  age_band  num_of_prev_attempts  studied_credits  disability  final_result
AAA          2013J              11391       M       East Anglian Region   HE Qualification       90-100%   55<=      0                     240              N           Pass            1
EEE          2014J              649843      M       London Region         A Level or Equivalent  10-20     0-35      0                     60               N           Pass            1
                                649783      M       London Region         A Level or Equivalent  20-30%    0-35      0                     120              N           Withdrawn       1
                                649755      M       South West Region     Lower Than A Level     30-40%    0-35      0                     60               N           Withdrawn       1
                                649738      M       East Anglian Region   HE Qualification       20-30%    35-55     0                     60               N           Pass            1
                                                                                                                                                                                       ..
CCC          2014J              182854      M       West Midlands Region  A Level or Equivalent  40-50%    0-35      0                     80               Y           Pass            1
                                181861      F       South East Region     Lower Than A Level     90-100%   35-55     0                     60               N           Pass            1
                                178072      M       South East Region     A Level or Equivalent  0-10%     0-35      1                     150              N           Pass            1
                                175638      M       North Western Region  Lower Than A Level     0-10%     0-35      0                     90               N           Fail            1
GGG          2014J              2684003     F       Yorkshire Region      HE Qualification       50-60%    35-55     0                     30               N           Distinction     1
Name: count, Length: 31482, dtype: int64


registration.head()
  code_module code_presentation  id_student  date_registration  \
0         AAA             2013J       11391             -159.0
1         AAA             2013J       28400              -53.0
2         AAA             2013J       30268              -92.0
3         AAA             2013J       31604              -52.0
4         AAA             2013J       32885             -176.0

   date_unregistration
0                  NaN
1                  NaN
2                 12.0
3                  NaN
4                  NaN
registration.shape
(32593, 5)

registration.describe()
       code_module code_presentation    id_student  date_registration  \
count        32593             32593  3.259300e+04       32548.000000
unique           7                 4           NaN                NaN
top            BBB             2014J           NaN                NaN
freq          7909             11260           NaN                NaN
mean           NaN               NaN  7.066877e+05         -69.411300
std            NaN               NaN  5.491673e+05          49.260522
min            NaN               NaN  3.733000e+03        -322.000000
25%            NaN               NaN  5.085730e+05        -100.000000
50%            NaN               NaN  5.903100e+05         -57.000000
75%            NaN               NaN  6.444530e+05         -29.000000
max            NaN               NaN  2.716795e+06         167.000000

        date_unregistration
count          10072.000000
unique                  NaN
top                     NaN
freq                    NaN
mean              49.757645
std               82.460890
min             -365.000000
25%               -2.000000
50%               27.000000
75%              109.000000
max              444.000000

registration.isna().sum()
code_module                0
code_presentation          0
id_student                 0
date_registration         45
date_unregistration    22521
dtype: int64

registration.value_counts()
code_module  code_presentation  id_student  date_registration  date_unregistration
AAA          2013J              30268       -92.0               12.0                  1
EEE          2013J              388252      -101.0              97.0                  1
                                336277      -32.0               47.0                  1
                                339353      -81.0              -75.0                  1
                                348708      -113.0              0.0                   1
                                                                                     ..
CCC          2014B              2383036     -235.0             -49.0                  1
                                2384615     -134.0             -89.0                  1
                                2384687     -92.0               44.0                  1
                                2389754     -22.0               101.0                 1
GGG          2014J              2679821     -49.0               101.0                 1
Name: count, Length: 10033, dtype: int64


student_vle.head()
  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1
student_vle.shape
(10655280, 6)

student_vle.describe()
       code_module code_presentation    id_student       id_site  \
count     10655280          10655280  1.065528e+07  1.065528e+07
unique           7                 4           NaN           NaN
top            FFF             2014J           NaN           NaN
freq       4014499           3619452           NaN           NaN
mean           NaN               NaN  7.333336e+05  7.383234e+05
std            NaN               NaN  5.827060e+05  1.312196e+05
min            NaN               NaN  6.516000e+03  5.267210e+05
25%            NaN               NaN  5.077430e+05  6.735190e+05
50%            NaN               NaN  5.882360e+05  7.300690e+05
75%            NaN               NaN  6.464840e+05  8.770300e+05
max            NaN               NaN  2.698588e+06  1.049562e+06

                date     sum_click
count   1.065528e+07  1.065528e+07
unique           NaN           NaN
top              NaN           NaN
freq             NaN           NaN
mean    9.517400e+01  3.716946e+00
std     7.607130e+01  8.849047e+00
min    -2.500000e+01  1.000000e+00
25%     2.500000e+01  1.000000e+00
50%     8.600000e+01  2.000000e+00
75%     1.560000e+02  3.000000e+00
max     2.690000e+02  6.977000e+03

student_vle.isna().sum()
code_module          0
code_presentation    0
id_student           0
id_site              0
date                 0
sum_click            0
dtype: int64

student_vle.value_counts()
code_module  code_presentation  id_student  id_site  date  sum_click
FFF          2013B              282879      527106   60    1            6
                                546583      527108   75    1            6
             2013J              601180      716439   80    1            6
                                597787      716437   67    1            6
                                602713      716436   72    1            6
                                                                       ..
DDD          2013J              342100      673537   161   2            1
                                                           4            1
                                                     163   3            1
                                                           8            1

In [34]:
#def basic_exploration(name, df):
#    print("{}.head()".format(name))
#    print(df.head())
#    print("{}.shape".format(name))
#    print(df.shape)
#    print("\n{}.describe()".format(name))
#    print(df.describe(include='all'))
#    print("\n{}.isna().sum()".format(name))
#    print(df.isna().sum())

#basic_exploration("assessments", assessments)

assessments.head()
  code_module code_presentation  id_assessment assessment_type   date  weight
0         AAA             2013J           1752             TMA   19.0    10.0
1         AAA             2013J           1753             TMA   54.0    20.0
2         AAA             2013J           1754             TMA  117.0    20.0
3         AAA             2013J           1755             TMA  166.0    20.0
4         AAA             2013J           1756             TMA  215.0    30.0
assessments.shape
(206, 6)

assessments.describe()
       code_module code_presentation  id_assessment assessment_type  \
count          206               206     206.000000             206
unique           7                 4            NaN               3
top            FFF             2014J            NaN             TMA
freq            52                57            NaN             106
mean           NaN               NaN   26473.975728             NaN
std            NaN               NaN   10098.625521             NaN
min            NaN               NaN    1752.000000             NaN
25%            NaN               NaN   15023.250000             NaN
50%            NaN               NaN   25364.500000             NaN
75%            NaN               NaN   34891.750000             NaN
max            NaN               NaN   40088.000000             NaN

              date      weight
count   195.000000  206.000000
unique         NaN         NaN
top            NaN         NaN
freq           NaN         NaN
mean    145.005128   20.873786
std      76.001119   30.384224
min      12.000000    0.000000
25%      71.000000    0.000000
50%     152.000000   12.500000
75%     222.000000   24.250000
max     261.000000  100.000000

assessments.isna().sum()
code_module           0
code_presentation     0
id_assessment         0
assessment_type       0
date                 11
weight                0
dtype: int64